version: '3.8'

services:
  cinema:
    build: .
    container_name: cinema
    depends_on:
      db-psql:
        condition: service_healthy
    ports:
      - "8080:8080"

  db-psql:
    image: postgres:16-alpine3.21
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    name: cinema