spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/cinema
    username: postgres
    password: lowkey
    driver: org.postgresql.Driver

app:
  admin:
    token: secretadmin123

springdoc:
  override-with-generic-response: false